name: Deploy

on:
  push:
    branches: [main]

jobs:
  terraform:
    uses: dilipsun/oidc-auth-workflow/.github/workflows/terraform-deploy.yml@main
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    permissions:
      id-token: write
      contents: read
